/*
 * Cookbook
 * RESTful Backend for Cookbook
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.cookbook.backend.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import java.util.ArrayList;
import java.util.List;
import org.braun.cookbook.web.model.Criteria;

/**
 * Keyword
 */
@JsonPropertyOrder({
  Keyword.JSON_PROPERTY_ID,
  Keyword.JSON_PROPERTY_PARENT_ID,
  Keyword.JSON_PROPERTY_NAME,
  Keyword.JSON_PROPERTY_NAME_UPPER,
  Keyword.JSON_PROPERTY_PATH,
  Keyword.JSON_PROPERTY_SYNONYMS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2026-03-15T12:45:26.012845663+01:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Keyword implements Criteria {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  private Long id;

  public static final String JSON_PROPERTY_PARENT_ID = "parentId";
  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  private Long parentId;

  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name;

  public static final String JSON_PROPERTY_NAME_UPPER = "nameUpper";
  @JsonProperty(JSON_PROPERTY_NAME_UPPER)
  private String nameUpper;

  public static final String JSON_PROPERTY_PATH = "path";
  @JsonProperty(JSON_PROPERTY_PATH)
  private String path;

  public static final String JSON_PROPERTY_SYNONYMS = "synonyms";
  @JsonProperty(JSON_PROPERTY_SYNONYMS)
  private List<String> synonyms = new ArrayList<>();

  public Keyword id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty(value = "id")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Keyword parentId(Long parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   **/
  @JsonProperty(value = "parentId")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Long getParentId() {
    return parentId;
  }

  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }

  public Keyword name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty(value = "name")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Keyword nameUpper(String nameUpper) {
    this.nameUpper = nameUpper;
    return this;
  }

  /**
   * Get nameUpper
   * @return nameUpper
   **/
  @JsonProperty(value = "nameUpper")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getNameUpper() {
    return nameUpper;
  }

  public void setNameUpper(String nameUpper) {
    this.nameUpper = nameUpper;
  }

  public Keyword path(String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   **/
  @JsonProperty(value = "path")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public Keyword synonyms(List<String> synonyms) {
    this.synonyms = synonyms;
    return this;
  }

  public Keyword addSynonymsItem(String synonymsItem) {
    if (this.synonyms == null) {
      this.synonyms = new ArrayList<>();
    }
    this.synonyms.add(synonymsItem);
    return this;
  }

  /**
   * Get synonyms
   * @return synonyms
   **/
  @JsonProperty(value = "synonyms")
  @ApiModelProperty(value = "")
  
  public List<String> getSynonyms() {
    return synonyms;
  }

  public void setSynonyms(List<String> synonyms) {
    this.synonyms = synonyms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Keyword keyword = (Keyword) o;
    return Objects.equals(this.id, keyword.id) &&
        Objects.equals(this.parentId, keyword.parentId) &&
        Objects.equals(this.name, keyword.name) &&
        Objects.equals(this.nameUpper, keyword.nameUpper) &&
        Objects.equals(this.path, keyword.path) &&
        Objects.equals(this.synonyms, keyword.synonyms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parentId, name, nameUpper, path, synonyms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Keyword {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameUpper: ").append(toIndentedString(nameUpper)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    synonyms: ").append(toIndentedString(synonyms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    @Override
    public boolean isEmpty() {
        return id == null || id == 0;
    }
}
