/*
 * Cookbook
 * RESTful Backend for Cookbook
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.cookbook.backend.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;

/**
 * RecipeShort
 */
@JsonPropertyOrder({
  RecipeShort.JSON_PROPERTY_ID,
  RecipeShort.JSON_PROPERTY_TITLE,
  RecipeShort.JSON_PROPERTY_PATH,
  RecipeShort.JSON_PROPERTY_KEYWORDS,
  RecipeShort.JSON_PROPERTY_RATING,
  RecipeShort.JSON_PROPERTY_SCORE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2026-03-20T15:54:59.576974925+01:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class RecipeShort   {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  private String id;

  public static final String JSON_PROPERTY_TITLE = "title";
  @JsonProperty(JSON_PROPERTY_TITLE)
  private String title;

  public static final String JSON_PROPERTY_PATH = "path";
  @JsonProperty(JSON_PROPERTY_PATH)
  private String path;

  public static final String JSON_PROPERTY_KEYWORDS = "keywords";
  @JsonProperty(JSON_PROPERTY_KEYWORDS)
  private List<String> keywords = new ArrayList<>();

  public static final String JSON_PROPERTY_RATING = "rating";
  @JsonProperty(JSON_PROPERTY_RATING)
  private Integer rating;

  public static final String JSON_PROPERTY_SCORE = "score";
  @JsonProperty(JSON_PROPERTY_SCORE)
  private Double score;

  public RecipeShort id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty(value = "id")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RecipeShort title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   **/
  @JsonProperty(value = "title")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public RecipeShort path(String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   **/
  @JsonProperty(value = "path")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public RecipeShort keywords(List<String> keywords) {
    this.keywords = keywords;
    return this;
  }

  public RecipeShort addKeywordsItem(String keywordsItem) {
    if (this.keywords == null) {
      this.keywords = new ArrayList<>();
    }
    this.keywords.add(keywordsItem);
    return this;
  }

  /**
   * Get keywords
   * @return keywords
   **/
  @JsonProperty(value = "keywords")
  @ApiModelProperty(value = "")
  
  public List<String> getKeywords() {
    return keywords;
  }

  public void setKeywords(List<String> keywords) {
    this.keywords = keywords;
  }

  public RecipeShort rating(Integer rating) {
    this.rating = rating;
    return this;
  }

  /**
   * Get rating
   * @return rating
   **/
  @JsonProperty(value = "rating")
  @ApiModelProperty(value = "")
  
  public Integer getRating() {
    return rating;
  }

  public void setRating(Integer rating) {
    this.rating = rating;
  }

  public RecipeShort score(Double score) {
    this.score = score;
    return this;
  }

  /**
   * Get score
   * @return score
   **/
  @JsonProperty(value = "score")
  @ApiModelProperty(value = "")
  
  public Double getScore() {
    return score;
  }

  public void setScore(Double score) {
    this.score = score;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipeShort recipeShort = (RecipeShort) o;
    return Objects.equals(this.id, recipeShort.id) &&
        Objects.equals(this.title, recipeShort.title) &&
        Objects.equals(this.path, recipeShort.path) &&
        Objects.equals(this.keywords, recipeShort.keywords) &&
        Objects.equals(this.rating, recipeShort.rating) &&
        Objects.equals(this.score, recipeShort.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, path, keywords, rating, score);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipeShort {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}