/*
 * Cookbook
 * RESTful Backend for Cookbook
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.braun.cookbook.backend.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import org.apache.commons.lang3.StringUtils;
import org.braun.cookbook.web.model.Criteria;

/**
 * Suggestion
 */
@JsonPropertyOrder({
    Suggestion.JSON_PROPERTY_NAME,
    Suggestion.JSON_PROPERTY_FREQUENCY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2026-03-25T09:47:42.223211589+01:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Suggestion implements Criteria {

    public static final String JSON_PROPERTY_NAME = "name";
    @JsonProperty(JSON_PROPERTY_NAME)
    private String name;

    public static final String JSON_PROPERTY_FREQUENCY = "frequency";
    @JsonProperty(JSON_PROPERTY_FREQUENCY)
    private Long frequency;

    public Suggestion() {
    }

    public Suggestion(String name, Long frequency) {
        this.name = name;
        this.frequency = frequency;
    }

    public Suggestion name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
   *
     */
    @JsonProperty(value = "name")
    @ApiModelProperty(required = true, value = "")
    @NotNull
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Suggestion frequency(Long frequency) {
        this.frequency = frequency;
        return this;
    }

    /**
     * Get frequency
     *
     * @return frequency
   *
     */
    @JsonProperty(value = "frequency")
    @ApiModelProperty(required = true, value = "")
    @NotNull
    public Long getFrequency() {
        return frequency;
    }

    public void setFrequency(Long frequency) {
        this.frequency = frequency;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Suggestion suggestion = (Suggestion) o;
        return Objects.equals(this.name, suggestion.name)
                && Objects.equals(this.frequency, suggestion.frequency);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, frequency);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Suggestion {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public boolean isEmpty() {
        return StringUtils.isBlank(name);
    }
}
